
version: 2

models:
  - name: dim_brazil
    description: "A starter dbt model"
    columns:
      - name: continent
        description: "The continent of the country"

      - name: country_name
        description: "The name of the country"
        
      - name: city_name
        description: "The name of the city"

      - name: city_population
        description: "The population count of the city"
      
      - name: "language"
        description: "The language of the city"

      - name: percentage
        description: "The percentage of the language"